Repository tripal/tripal, pull requests merged in 2018-07, with the labels that each got.

#497 Update Introduction and Installation in README.md
  README.md
Labels: documentation

#502 fix OBO existing OBO fieldset callback
  tripal_chado/includes/TripalImporter/OBOImporter.inc
Labels: Only 1 Review Needed, Reviewer #1 Approval, bug

#508 Publication layout fix
  tripal_ds/includes/tripal_ds.ds.inc
Labels: Only 1 Review Needed, bug

#521 Bug Fix: Sequence Coordinates field only showed the last location.
  tripal_chado/includes/TripalFields/data__sequence_coordinates/data__sequence_coordinates.inc
  tripal_chado/includes/TripalFields/data__sequence_coordinates/data__sequence_coordinates_formatter.inc
Labels: Only 1 Review Needed, bug, testing requested
