Repository tripal/tripal, pull requests merged in 2018-09, with the labels that each got.

#547 Remote fields not working if content type name changed.
  tripal_ws/includes/TripalFields/remote__data/remote__data.inc
  tripal_ws/includes/TripalWebService/TripalContentService_v0_1.inc
Labels: Reviewer #1 Approval, Reviewer #2 Approval, URGENT!, release blocker, tripal-7.x-3.x

#624 Fix undefined property bundle error
  tripal_ds/tripal_ds.module
Labels: Only 1 Review Needed, release blocker, tripal-7.x-3.x

#613 Tripal Field getValueList Method
  composer.lock
  tests/tripal_chado/fields/ChadoFieldGetValuesListTest.php
  tripal/includes/TripalFields/TripalField.inc
  tripal_chado/includes/TripalFields/ChadoField.inc
Labels: Reviewer #1 Approval, Reviewer #2 Approval, testing requested, tripal-7.x-3.x

#621 PHP Undefined Property Notice in TripalEntityController
  tripal/includes/TripalEntityController.inc
Labels: Reviewer #1 Approval, Reviewer #2 Approval, potential bug, tripal-7.x-3.x

#630 629 dev guide videos
  docs/dev_guide.rst
  docs/dev_guide/tutorials.rst
Labels: Reviewer #1 Approval, documentation

#596 New Default Content Types
  tripal/api/tripal.entities.api.inc
  tripal/api/tripal.importer.api.inc
  tripal/includes/TripalEntityUIController.inc
  tripal/theme/css/tripal.css
  tripal_chado/includes/setup/tripal_chado.setup.inc
  tripal_chado/includes/tripal_chado.fields.inc
  tripal_chado/includes/tripal_chado.mapping.inc
  tripal_chado/includes/tripal_chado.semweb.inc
  tripal_chado/tripal_chado.install
Labels: Reviewer #1 Approval, Reviewer #2 Approval, URGENT!, enhancement, fix required, release blocker, tripal-7.x-3.x

#632 Added ChadoRecord class as a proposal for improved API functions
  tests/tripal_chado/api/ChadoRecordTest.php
  tripal_chado/api/ChadoRecord.inc
  tripal_chado/tripal_chado.module
Labels: Reviewer #1 Approval, Reviewer #2 Approval, URGENT!, enhancement, release blocker, tripal-7.x-3.x

#644 remove php tag and fix site build to use php syntax highlighting prop…
  docs/conf.py
  docs/dev_guide/custom_field/manual_field_creation.rst
  docs/dev_guide/custom_field/select_vocab_terms.rst
  docs/dev_guide/custom_web_services.rst
Labels: Only 1 Review Needed, Reviewer #1 Approval, documentation

#651 Brand ReadtheDocs
  docs/_static/hexagon_pattern.png
  docs/_static/small_logoonly.png
  docs/_static/theme_overrides.css
  docs/conf.py
Labels: Ready for Review, Reviewer #1 Approval, Reviewer #2 Approval

#654 remove extra comma and thus extra column from creating content guide table
  docs/user_guide/creating_content.rst
Labels: Only 1 Review Needed, documentation

#643 503 custom data loader
  docs/dev_guide/custom_data_loader.0.png
  docs/dev_guide/custom_data_loader.1.oob_file_interface.png
  docs/dev_guide/custom_data_loader.2.oob_analysis_select.png
  docs/dev_guide/custom_data_loader.3.cvterm_select.png
  docs/dev_guide/custom_data_loader.rst
Labels: documentation

#659 657 fix broken chado property API calls and add unit tests for each
  tests/tripal_chado/api/TripalChadoPropertyAPITest.php
  tripal_chado/api/tripal_chado.property.api.inc
Labels: Ready for Review, Reviewer #1 Approval, Reviewer #2 Approval, bug

#627 New OBO Importer
  tests/tripal_chado/example_files/test.obo
  tests/tripal_chado/example_files/test.update.obo
  tests/tripal_chado/loaders/GFF3ImporterTest.php
  tests/tripal_chado/loaders/OBOImporterTest.php
  tripal/api/tripal.DEPRECATED.api.inc
  tripal/api/tripal.notice.api.inc
  tripal/api/tripal.terms.api.inc
  tripal/includes/TripalImporter.inc
  tripal/includes/TripalJob.inc
  tripal/includes/tripal.jobs.inc
  tripal/includes/tripal.term_lookup.inc
  tripal_chado/api/ChadoRecord.inc
  tripal_chado/api/modules/tripal_chado.cv.api.inc
  tripal_chado/api/modules/tripal_chado.module.DEPRECATED.api.inc
  tripal_chado/api/tripal_chado.mviews.api.inc
  tripal_chado/files/tcontact.obo
  tripal_chado/files/tpub.obo
  tripal_chado/includes/TripalImporter/OBOImporter.inc
  tripal_chado/includes/setup/tripal_chado.chado_vx_x.inc
  tripal_chado/includes/setup/tripal_chado.setup.inc
  tripal_chado/includes/tripal_chado.bundle.inc
  tripal_chado/includes/tripal_chado.fields.inc
  tripal_chado/includes/tripal_chado.install.inc
  tripal_chado/includes/tripal_chado.semweb.inc
  tripal_chado/includes/tripal_chado.vocab_storage.inc
  tripal_chado/tripal_chado.install
Labels: Reviewer #1 Approval, Reviewer #2 Approval, URGENT!, affects multiple users, bug, discussion, enhancement, ontologies, performance, release blocker, tripal-7.x-3.x

#653 Delete removed entity from chado_bio_data_x
  tripal_chado/includes/tripal_chado.entity.inc
Labels: Only 1 Review Needed, Reviewer #1 Approval, release blocker

#667 fix features in wrong order leading to wrong CDS sequences (fixes #415)
  tripal_chado/api/modules/tripal_chado.feature.api.inc
Labels: Only 1 Review Needed, Reviewer #1 Approval

#662 Added a test suite video to the video tutorials section
  docs/dev_guide/tutorials.rst
Labels: Only 1 Review Needed, documentation

#637 633 implement drupal home env in install documentation
  docs/user_guide.rst
  docs/user_guide/bulk_loader.rst
  docs/user_guide/example_genomics/pub_import.rst
  docs/user_guide/install_tripal.rst
  docs/user_guide/install_tripal/automating_job_execution.rst
  docs/user_guide/install_tripal/manual_install/install_drupal.rst
  docs/user_guide/install_tripal/manual_install/install_prereqs.rst
  docs/user_guide/install_tripal/manual_install/install_tripal.rst
  docs/user_guide/install_tripal/rapid_install.rst
  docs/user_guide/install_tripal/upgrade_from_tripal2.rst
  docs/user_guide/job_management.rst
  docs/user_guide/mviews.rst
  docs/user_guide/web_services.rst
  tripal_chado/api/tripal_chado.variables.api.inc
Labels: Ready for Review, Reviewer #1 Approval, Reviewer #2 Approval, documentation

#679 remove extra checks from tripal ws file loader
  tripal_ws/api/tripal_ws.api.inc
Labels: Only 1 Review Needed, Reviewer #1 Approval, tripal-7.x-3.x

#675 Check that the field name exists before continuing
  tripal/includes/TripalFieldDownloaders/TripalCSVDownloader.inc
  tripal/includes/TripalFieldDownloaders/TripalTabDownloader.inc
Labels: Only 1 Review Needed, Reviewer #1 Approval, tripal-7.x-3.x

#641 ChadoSchema class and chado compliance checking
  docs/dev_guide.rst
  docs/dev_guide/chado.rst
  tests/tripal_chado/api/ChadoComplianceTest.php
  tests/tripal_chado/api/ChadoSchemaTest.php
  tripal_chado/api/ChadoSchema.inc
  tripal_chado/api/tripal_chado.schema_v1.2.api.inc
  tripal_chado/api/tripal_chado.schema_v1.3.api.inc
Labels: Ready for Review, Reviewer #1 Approval, Reviewer #2 Approval, enhancement

#691 Fixed instructions for the field
  tripal_ws/includes/TripalFields/remote__data/remote__data.inc
  tripal_ws/includes/TripalWebService/TripalContentService_v0_1.inc
Labels: Only 1 Review Needed, Reviewer #1 Approval, URGENT!, release blocker, tripal-7.x-3.x

#685 Fix a few warnings
  tripal/api/tripal.entities.api.inc
  tripal_chado/api/modules/tripal_chado.cv.api.inc
  tripal_chado/includes/TripalImporter/OBOImporter.inc
  tripal_chado/includes/setup/tripal_chado.setup.inc
  tripal_chado/includes/tripal_chado.semweb.inc
  tripal_chado/tripal_chado.install
Labels: Only 1 Review Needed, Reviewer #1 Approval, tripal-7.x-3.x

#673 670 github update templates
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  docs/README.md
Labels: Reviewer #1 Approval, Reviewer #2 Approval, documentation
