Repository tripal/tripal, pull requests merged in 2019-02, with the labels that each got.

#845 Update drush install to be specific to Drush 8.
  docs/user_guide/install_tripal/drush_installation.rst
Labels: Only 1 Review Needed, documentation

#840 add ajax formatter guide
  docs/dev_guide/custom_field.rst
  docs/dev_guide/custom_field/ajax_custom_formatter.rst
Labels: Reviewer #1 Approval, documentation

#847 Update job_management.rst
  docs/user_guide/job_management.rst
Labels: Only 1 Review Needed, documentation

#827 Allow complex filtering when only one level is set
  tests/tripal_chado/api/ChadoQueryTest.php
  tripal_chado/api/tripal_chado.query.api.inc
Labels: Reviewer #1 Approval, Reviewer #2 Approval

#849 Update install_drupal.rst
  docs/user_guide/install_tripal/manual_install/install_drupal.rst
  docs/user_guide/install_tripal/server_setup/ubuntu_18.04.rst
Labels: Only 1 Review Needed, Reviewer #1 Approval, documentation, good first issue

#848 Add instructions on the custom widget FK relationship magic.
  docs/dev_guide/custom_field/custom_widget.rst
Labels: Reviewer #1 Approval, Reviewer #2 Approval, documentation

#856 Add Module Rating to the docs.
  docs/dev_guide/best_practices.rst
  docs/extensions.rst
  docs/extensions/Tripal-Bronze.png
  docs/extensions/Tripal-Bronze.svg
  docs/extensions/Tripal-Gold.png
  docs/extensions/Tripal-Gold.svg
  docs/extensions/Tripal-Silver.png
  docs/extensions/Tripal-Silver.svg
  docs/extensions/instructions.rst
  docs/extensions/module_rating.rst
Labels: Reviewer #1 Approval, Reviewer #2 Approval, documentation, tripal-7.x-3.x

#862 Minor typo in module rating instructions
  docs/extensions/module_rating.rst
Labels: Only 1 Review Needed, Reviewer #1 Approval, documentation
