Repository tripal/tripal, pull requests merged in 2019-06, with the labels that each got.

#944 Tripal Blast: Request for Gold Badge Status
  docs/extensions/3rd_party.rst
Labels: Reviewer #1 Approval

#917 759 3x tripal registration form
  tripal/includes/tripal.registration.inc
  tripal/tripal.module
Labels: Reviewer #1 Approval, Reviewer #2 Approval, enhancement, tripal-7.x-3.x

#948 Update job_management.rst (extracted directory name correction)
  docs/user_guide/job_management.rst
Labels: Only 1 Review Needed, documentation

#953 Update governance.rst
  docs/contributing/governance.rst
Labels: Only 1 Review Needed, documentation
