Repository tripal/tripal, pull requests merged in 2019-01, with the labels that each got.

#806 Fix for disappearing fields in tables that are ajax loaded.
  tripal/api/tripal.fields.api.inc
  tripal/includes/TripalEntityController.inc
  tripal/includes/TripalEntityUIController.inc
  tripal/includes/tripal.entity.inc
  tripal/includes/tripal.fields.inc
  tripal/includes/tripal.user.inc
  tripal/tripal.module
  tripal_chado/includes/TripalFields/data__sequence/data__sequence_formatter.inc
  tripal_chado/includes/TripalFields/sbo__relationship/sbo__relationship_formatter.inc
  tripal_chado/includes/TripalFields/schema__publication/schema__publication_formatter.inc
Labels: Reviewer #1 Approval, Reviewer #2 Approval, URGENT!, bug, tripal-7.x-3.x

#814 Unable to create cvterm-based content type
  tripal_chado/includes/tripal_chado.field_storage.inc
  tripal_chado/includes/tripal_chado.fields.inc
Labels: Reviewer #1 Approval, Reviewer #2 Approval, bug, tripal-7.x-3.x

#817 check field permissions explicitly if configured
  tripal_ws/includes/TripalWebService/TripalContentService_v0_1.inc
Labels: Only 1 Review Needed, Ready for Review, Reviewer #1 Approval

#834 Resolve travis mem
  tests/tripal_chado/loaders/TaxonomyImporterTest.php
  tripal_chado/includes/TripalImporter/TaxonomyImporter.inc
Labels: Only 1 Review Needed, Reviewer #1 Approval, URGENT!, affects multiple users

#828 Cache file scan for TripalFields
  tripal/api/tripal.fields.api.inc
Labels: Reviewer #1 Approval, Reviewer #2 Approval, affects multiple users, bug

#835 Do not create DB records in sbo__relationship_widget test
  composer.json
  tests/tripal_chado/fields/sbo__relationship_widgetTest.php
Labels: Reviewer #1 Approval, Reviewer #2 Approval

#825 Trigger a window resize event when the tripal_ds animation is complete
  tripal_ds/theme/js/tripal_ds.js
Labels: Reviewer #1 Approval, Reviewer #2 Approval

#833 Added phylotree module for tree visualisation.
  docs/extensions/visualization.rst
Labels: Only 1 Review Needed, documentation, waiting on submitter

#839 Fix multiple close icons with ajax calls
  tripal_ds/theme/js/tripal_ds.js
Labels: Ready for Review, Reviewer #1 Approval
