Repository tripal/tripal, pull requests merged in 2019-03, with the labels that each got.

#829 Fix #790 (+ revert #799) : Alias issues
  tripal/api/tripal.entities.api.inc
Labels: Reviewer #1 Approval, Reviewer #2 Approval

#855 Fix #854 (empty field behaviour)
  tripal_chado/includes/TripalFields/schema__alternate_name/schema__alternate_name_formatter.inc
  tripal_chado/includes/TripalFields/schema__publication/schema__publication_formatter.inc
Labels: Reviewer #1 Approval, Reviewer #2 Approval

#865 Add gold rating to Tripal HQ
  docs/extensions/administrative.rst
Labels: Reviewer #1 Approval

#875 Add php 7.2 and 7.3 and remove 7.0
  .travis.yml
Labels: Reviewer #1 Approval, Reviewer #2 Approval

#873 Fix loop error
  tripal_chado/includes/tripal_chado.fields.inc
Labels: Reviewer #1 Approval, Reviewer #2 Approval

#882 Allows query object to be dumped as a string.
  tripal/includes/TripalFieldQuery.inc
Labels: Reviewer #1 Approval, Reviewer #2 Approval

#880 Typo mistake in the entity URL
  tripal/includes/tripal.entity.inc
Labels: Reviewer #1 Approval, Reviewer #2 Approval

#869 Request for gold badge status for tripal galaxy module
  docs/extensions/3rd_party.rst
Labels: Reviewer #1 Approval

#883 Add error checking in chado_get_minimal_pub_info
  tripal_chado/api/modules/tripal_chado.pub.api.inc
Labels: Only 1 Review Needed, Reviewer #1 Approval

#886 call fgets on open file instead of path
  docs/dev_guide/custom_data_loader.rst
Labels: Only 1 Review Needed, documentation

#895 add menu item for creating Tripal content
  tripal/includes/TripalEntityUIController.inc
  tripal/tripal.module
Labels: Reviewer #1 Approval, Reviewer #2 Approval

#902 Fixes issue #176
  tripal_views/includes/tripal_views_integration_UI.inc
Labels: Only 1 Review Needed, Reviewer #1 Approval

#897 Sink chad.db creation link to match chado.cv
  tripal_chado/tripal_chado.module
Labels: Only 1 Review Needed

#900 Add more error checking to the publish form.
  tripal_chado/includes/tripal_chado.publish.inc
Labels: Only 1 Review Needed, tripal-7.x-3.x

#901 Add term check when retrieving term details.
  tripal/api/tripal.terms.api.inc
Labels: Only 1 Review Needed, Reviewer #1 Approval, tripal-7.x-3.x

#903 Travis Missing Tripal2 Modules Fix
  .travis.yml
Labels: Only 1 Review Needed

#850 Bug Fix: Update hook_views_data_alter() to fix issue #789
  tripal_chado_views/tripal_chado_views.views.inc
Labels: Reviewer #1 Approval, Reviewer #2 Approval

#906 URGENT: Fix Tripal 2 => 3 upgrade
  tripal/tripal.install
Labels: Reviewer #1 Approval, Reviewer #2 Approval
