Repository tripal/tripal, pull requests merged in 2019-07, with the labels that each got.

#968 PHP 7.2 migration displays a "Countable" error
  tripal_stock/theme/templates/tripal_stock_collections.tpl.php
  tripal_stock/theme/templates/tripal_stock_publications.tpl.php
Labels: Only 1 Review Needed, Reviewer #1 Approval

#972 Case sensitive chado_query function
  tripal_chado/api/tripal_chado.query.api.inc
  tripal_chado/includes/ChadoPrefixExtender.inc
Labels: Only 1 Review Needed, bug

#955 Add support to override the default button on Tripal importers.
  tripal/includes/TripalImporter.inc
  tripal/includes/tripal.importer.inc
Labels: Only 1 Review Needed, Ready for Review
