Repository tripal/tripal, pull requests merged in 2020-10, with the labels that each got.

#1096 Use property exists instead of array_key_exists
  tripal_chado/api/tripal_chado.variables.api.inc
Labels: Hacktoberfest, Reviewer #1 Approval, enhancement

#1097 Update visualization.rst
  docs/extensions/visualization.rst
Labels: Badge Request, Hacktoberfest

#1099 Analyzed Phenotypes Gold Badge Request
  docs/extensions/visualization.rst
Labels: Badge Request, hacktoberfest-accepted

#1103 Bug fix that makes GFFImporter caching of features work correctly
  tripal_chado/includes/TripalImporter/GFF3Importer.inc
Labels: hacktoberfest-accepted

#1087 Oboimporter20201001
  tripal_chado/includes/TripalImporter/OBOImporter.inc
Labels: Reviewer #1 Approval, bug, hacktoberfest-accepted, tripal-7.x-3.x

#1090 Alter hooks for field/field instance info arrays
  tripal/api/tripal.entities.api.inc
  tripal/api/tripal.fields.api.inc
  tripal/includes/tripal.admin_blocks.inc
Labels: bug, hacktoberfest-accepted, tripal-7.x-3.x

#1095 Infraspecific nomenclature updates in tripal_chado.organism.api.inc
  tripal_chado/api/modules/tripal_chado.organism.api.inc
Labels: Reviewer #1 Approval, bug, hacktoberfest-accepted, tripal-7.x-3.x

#1105 Fix for long running sio__references field
  tripal_chado/api/tripal_chado.variables.api.inc
  tripal_chado/includes/TripalFields/sio__references/sio__references.inc
  tripal_chado/includes/TripalFields/sio__references/sio__references_formatter.inc
Labels: Reviewer #1 Approval, bug, hacktoberfest-accepted, tripal-7.x-3.x

#1107 October corrections for typos
  docs/dev_guide/custom_field/manual_field_creation.rst
  docs/user_guide/install_tripal/custom_theme.rst
  legacy/tripal_core/api/tripal_core.chado_nodes.properties.api.inc
  legacy/tripal_core/api/tripal_core.chado_nodes.relationships.api.inc
  legacy/tripal_phylogeny/tripal_phylogeny.drush.inc
  tripal/tripal.module
  tripal_chado/api/modules/tripal_chado.cv.api.inc
  tripal_chado/api/modules/tripal_chado.db.api.inc
  tripal_chado/api/modules/tripal_chado.phylotree.api.inc
  tripal_chado/includes/TripalFields/sbo__relationship/sbo__relationship_formatter.inc
  tripal_chado/includes/tripal_chado.fields.inc
  tripal_chado/includes/tripal_chado.phylotree.inc
  tripal_daemon/theme/tripal_daemon.log_block.css
  tripal_ws/includes/TripalFields/remote__data/remote__data_formatter.inc
  tripal_ws/includes/TripalWebService.inc
  tripal_ws/includes/TripalWebServiceCollection.inc
Labels: hacktoberfest-accepted, tripal-7.x-3.x

#1106 Fixes related to test testGFFImporterAttributeProperty()
  tests/tripal_chado/data/small_gene.gff
  tests/tripal_chado/loaders/GFF3ImporterTest.php
Labels: hacktoberfest-accepted

#1109 Tripal field URLs made clickable
  tripal_chado/includes/TripalFields/chado_linker__prop/chado_linker__prop_formatter.inc
Labels: hacktoberfest-accepted

#1113 Added fix for issue #1112
  tripal_ws/includes/TripalWebService/TripalContentService_v0_1.inc
Labels: Reviewer #1 Approval, bug, hacktoberfest-accepted, tripal-7.x-3.x

#1121 Update in_development.rst
  docs/extensions/in_development.rst
  docs/extensions/visualization.rst
Labels: documentation, hacktoberfest-accepted

#1123 All unit tests pass, remove remote dependencies, modification of faulty tests
  tests/tripal_chado/data/empty_landmarks.fasta
  tests/tripal_chado/data/gff_duplicate_ids.gff
  tests/tripal_chado/data/gff_protein_generation.gff
  tests/tripal_chado/loaders/GFF3ImporterTest.php
Labels: hacktoberfest-accepted

#1124 Added extra ID validation within GFF3 loader based on GFF3 specs, 2 unit tests for ID, 1 unit test for start end reversal
  tests/tripal_chado/data/gff_invalidstartend.gff
  tests/tripal_chado/data/gff_rightarrow_id.gff
  tests/tripal_chado/data/gff_unescaped_ids.gff
  tests/tripal_chado/loaders/GFF3ImporterTest.php
  tripal_chado/includes/TripalImporter/GFF3Importer.inc
Labels: hacktoberfest-accepted
