Repository tripal/tripal, pull requests merged in 2020-04, with the labels that each got.

#1039 Fixes for issue #1038
  tripal/includes/TripalEntityCollection.inc
  tripal/includes/TripalJob.inc
  tripal_chado/includes/TripalFields/sio__references/sio__references.inc
  tripal_chado/includes/TripalFields/sio__references/sio__references_formatter.inc
Labels: bug, tripal-7.x-3.x

#1042 Documentation typo for Tripal Fields tutorial
  docs/dev_guide/custom_field/manual_field_creation.rst
Labels: Reviewer #1 Approval, documentation

#1044 Restoration of functionality of National Ag Library publication loader
  tripal_chado/api/modules/tripal_chado.pub.api.inc
  tripal_chado/includes/loaders/tripal_chado.pub_importer_AGL.inc
  tripal_chado/includes/loaders/tripal_chado.pub_importers.inc
Labels: Reviewer #1 Approval, Reviewer #2 Approval
