Repository tripal/tripal, pull requests merged in 2020-05, with the labels that each got.

#1047 Adding Private BioData module
  docs/extensions/administrative.rst
Labels: Badge Request, Reviewer #1 Approval

#1056 National Ag Library publication loader HTML entity bugfix
  tripal_chado/includes/loaders/tripal_chado.pub_importer_AGL.inc
Labels: Reviewer #1 Approval, Reviewer #2 Approval

#1062 Fix typos
  docs/dev_guide/chado.rst
  docs/dev_guide/custom_field.rst
  docs/dev_guide/custom_field/custom_formatter.rst
  docs/dev_guide/custom_field/manual_field_creation.rst
  docs/dev_guide/custom_field/select_vocab_terms.rst
  docs/dev_guide/data_structures.rst
  docs/dev_guide/introduction.rst
  docs/user_guide/bulk_loader.rst
  docs/user_guide/content_types/configuring_page_display.rst
  docs/user_guide/content_types/field_loading.rst
  docs/user_guide/install_tripal/drupal_home.rst
  docs/user_guide/job_management.rst
  docs/user_guide/searching/search_api.rst
Labels: Reviewer #1 Approval
