Repository tripal/tripal, pull requests merged in 2020-03, with the labels that each got.

#1029 Registration form fixes
  tripal/includes/tripal.registration.inc
  tripal/tripal.module
Labels: bug

#1037 NCBI API key
  tripal_chado/includes/loaders/tripal_chado.pub_importer_PMID.inc
  tripal_chado/includes/loaders/tripal_chado.pub_importers.inc
Labels: Reviewer #1 Approval

#1021 Unpublish ALL orphaned content from all bundles
  tripal/includes/TripalBundleController.inc
  tripal/includes/tripal.unpublish_orphans.inc
Labels: Reviewer #1 Approval, Reviewer #2 Approval
