Repository tripal/tripal, pull requests merged in 2025-07, with the labels that each got.

#2228 Replace invalid placeholders
  tripal/src/api/tripal.upload.api.php
  tripal_chado/src/Plugin/TripalImporter/OBOImporter.php
  tripal_chado/src/api/ChadoSchema.php
  tripal_chado/src/api/tripal_chado.cv.api.php
  tripal_chado/src/api/tripal_chado.query.api.php
Labels: Group 0 - Maintenance | Docker | Misc, Priority - Medium

#2231 Updating our repo to use Qlty Cloud instead of CodeClimate
  .codeclimate.yml
  .github/workflows/ALL-testCoverage-codeclimate.yml
  .github/workflows/ALL-testCoverage-qltycloud.yml
  .gitignore
  .qlty/.gitignore
  .qlty/configs/.hadolint.yaml
  .qlty/configs/.shellcheckrc
  .qlty/configs/.yamllint.yaml
  .qlty/qlty.toml
  README.md
Labels: Group 0 - Maintenance | Docker | Misc, Group 8 - Other Integrations, Easy PR Review 😀, Priority - High

#2233 Escape special characters in usernames that cause issues in generated drush commands
  tripal/src/Services/TripalJob.php
  tripal/src/api/tripal.jobs.api.php
Labels: Easy PR Review 😀

#2241 Fix wrong config in nightly PHPUnit runs for Drupal 10.x
  .github/workflows/MAIN-phpunit-php8.1_D10_3x.yml
  .github/workflows/MAIN-phpunit-php8.1_D10_4x.yml
  .github/workflows/MAIN-phpunit-php8.1_D10_5x.yml
  .github/workflows/MAIN-phpunit-php8.2_D10_3x.yml
  .github/workflows/MAIN-phpunit-php8.2_D10_4x.yml
  .github/workflows/MAIN-phpunit-php8.2_D10_5x.yml
  .github/workflows/MAIN-phpunit-php8.3_D10_3x.yml
  .github/workflows/MAIN-phpunit-php8.3_D10_4x.yml
  .github/workflows/MAIN-phpunit-php8.3_D10_5x.yml
Labels: Group 9 - Automated Testing, Easy PR Review 😀

#2235 Adds request throttling option to the file retriever service 🐌
  tripal/src/Plugin/TripalPubLibrary/TripalPubLibraryPubMed.php
  tripal/src/Services/TripalFileRetriever.php
  tripal/tests/src/Kernel/Services/TripalFileRetriever/TripalFileRetrieverTest.php
  tripal_chado/src/Plugin/TripalImporter/TaxonomyImporter.php
Labels: Group 4 - Data Importing, Priority - High
