Repository tripal/tripal, pull requests merged in 2025-05, with the labels that each got.

#2200 Support Field group 4.0 semversion update
  .github/workflows/MAIN-composerInstall.yml
  composer.json
Labels: bug - confirmed, Group 0 - Maintenance | Docker | Misc, Priority - High

#2202 Fix wrong config for PHPUnit for Drupal < 11.x
  .github/workflows/ALL-phpunit.yml
Labels: Group 9 - Automated Testing, Easy PR Review 😀, Priority - High

#2204 pass drupalversion to docker
  .github/workflows/ALL-phpunit.yml
Labels: Group 9 - Automated Testing, Easy PR Review 😀

#2206 Fix gff loader inconsistent form
  tripal_chado/src/Plugin/TripalImporter/GFF3Importer.php
  tripal_chado/tests/src/Functional/Plugin/GFF3ImporterTest.php
Labels: Group 4 - Data Importing, Priority - Low
