Repository tripal/tripal, pull requests merged in 2025-09, with the labels that each got.

#2272 Updating TripalEntity and TripalEntityType to match coding standards.
  tripal/src/Entity/TripalEntity.php
  tripal/src/Entity/TripalEntityInterface.php
  tripal/src/Entity/TripalEntityType.php
  tripal/src/Entity/TripalEntityTypeInterface.php
Labels: Group 0 - Maintenance | Docker | Misc, Easy PR Review 😀, Priority - Medium

#2271 Editing single-hop property field fixed
  tripal/src/Entity/TripalEntity.php
  tripal_chado/src/TripalStorage/ChadoRecords.php
Labels: bug - confirmed, Group 1 - Tripal Content Types | Terms | Fields, Easy PR Review 😀, Priority - Medium

#2277 Update Test Coverage Workflow to run on 4.x
  .github/workflows/ALL-testCoverage-qltycloud.yml
Labels: bug - confirmed, Priority - URGENT!, Group 0 - Maintenance | Docker | Misc, Group 9 - Automated Testing, Easy PR Review 😀

#2279 Update Tripal Storage to current coding standards
  tripal/src/Plugin/TripalStorage/DrupalSqlStorage.php
  tripal/src/TripalStorage/BoolStoragePropertyType.php
  tripal/src/TripalStorage/DateTimeStoragePropertyType.php
  tripal/src/TripalStorage/IntStoragePropertyType.php
  tripal/src/TripalStorage/Interfaces/TripalStorageInterface.php
  tripal/src/TripalStorage/PluginManager/TripalStorageManager.php
  tripal/src/TripalStorage/RealStoragePropertyType.php
  tripal/src/TripalStorage/StoragePropertyBase.php
  tripal/src/TripalStorage/StoragePropertyTypeBase.php
  tripal/src/TripalStorage/StoragePropertyValue.php
  tripal/src/TripalStorage/TextStoragePropertyType.php
  tripal/src/TripalStorage/TripalStorageBase.php
  tripal/src/TripalStorage/VarCharStoragePropertyType.php
  tripal/tests/src/Kernel/Entity/TripalEntityFieldTest.php
  tripal/tests/src/Kernel/Entity/TripalEntityTest.php
  tripal/tests/src/Kernel/Entity/TripalEntityTokenFormatsTest.php
  tripal/tests/src/Kernel/TripalField/FieldType/TripalFieldTypeCRUDTest.php
  tripal/tests/src/Kernel/TripalField/FieldType/TripalFieldTypeSettingsTest.php
  tripal/tests/src/Kernel/TripalStorage/DrupalSqlStorageTest.php
  tripal/tests/src/Kernel/TripalStorage/PropertyBaseClassTest.php
  tripal/tests/src/Kernel/TripalStorage/PropertyTypeClassTest.php
  tripal/tests/src/Kernel/TripalStorage/PropertyValueClassTest.php
  tripal/tests/src/Kernel/TripalStorage/TripalStorageTest.php
  tripal_chado/src/Plugin/TripalStorage/ChadoStorage.php
  tripal_chado/src/TripalStorage/ChadoBoolStoragePropertyType.php
  tripal_chado/src/TripalStorage/ChadoBpCharStoragePropertyType.php
  tripal_chado/src/TripalStorage/ChadoDateTimeStoragePropertyType.php
  tripal_chado/src/TripalStorage/ChadoIntStoragePropertyType.php
  tripal_chado/src/TripalStorage/ChadoRealStoragePropertyType.php
  tripal_chado/src/TripalStorage/ChadoRecords.php
  tripal_chado/src/TripalStorage/ChadoTextStoragePropertyType.php
  tripal_chado/src/TripalStorage/ChadoVarCharStoragePropertyType.php
  tripal_chado/tests/src/Kernel/Entity/TripalEntityChadoFieldTest.php
  tripal_chado/tests/src/Kernel/Plugin/ChadoStorage/ChadoAnalysisDefaultTest.php
  tripal_chado/tests/src/Kernel/Plugin/ChadoStorage/ChadoContactDefaultTest.php
  tripal_chado/tests/src/Kernel/Plugin/ChadoStorage/ChadoLinkerPropertyDefaultTest.php
  tripal_chado/tests/src/Kernel/Plugin/ChadoStorage/ChadoStorageActions_ReadValueTest.php
  tripal_chado/tests/src/Kernel/Plugin/ChadoStorage/ChadoStorageActions_StoreIdTest.php
  tripal_chado/tests/src/Kernel/Plugin/ChadoStorage/ChadoStorageActions_StoreLinkTest.php
  tripal_chado/tests/src/Kernel/Plugin/ChadoStorage/ChadoStorageActions_StorePkeyTest.php
  tripal_chado/tests/src/Kernel/Plugin/ChadoStorage/ChadoStorageActions_StoreTest.php
  tripal_chado/tests/src/Kernel/Plugin/ChadoStorage/ChadoStorageDeleteValuesTest.php
  tripal_chado/tests/src/Kernel/Plugin/ChadoStorage/ChadoStorageFindValuesTest.php
  tripal_chado/tests/src/Kernel/Plugin/ChadoStorage/ChadoStorageLinkerFieldTest.php
  tripal_chado/tests/src/Kernel/Services/SyncTripalFieldStorage/SyncTripalFieldStorageTest.php
Labels: Group 2 - Data Storage | Tripal DBX | Chado

#2283 Fix invalid menu machine name
  tripal/tripal.install
Labels: Group 7 - Page Display, Easy PR Review 😀, Priority - Medium

#2251 Make Publication type property field unlimited cardinality
  tripal_chado/config/install/tripal.tripalfield_collection.general_chado.yml
  tripal_chado/src/Plugin/TripalImporter/PubSearchQueryImporter.php
Labels: Group 1 - Tripal Content Types | Terms | Fields, Easy PR Review 😀, Priority - Low

#2288 Resolve missing germplasm cvterms in automated testing environment
  tripal_chado/config/install/tripal.tripal_content_terms.chado_content_terms.yml
  tripal_chado/tests/fixtures/fill_chado_test_prepare.sql
  tripal_chado/tests/src/Kernel/Plugin/TripalImporter/OboImporter-TestInfo.yml
  tripal_chado/tests/src/Kernel/Plugin/TripalImporter/OboImporterTest.php
Labels: bug - confirmed, Priority - Release Blocker, Group 9 - Automated Testing, Easy PR Review 😀, Priority - Medium

#2294 Actually deprecate the Chado Query API in favour of Tripal DBX.
  phpunit.9.6.xml
  tripal_chado/src/api/tripal_chado.cv.api.php
  tripal_chado/src/api/tripal_chado.db.api.php
  tripal_chado/src/api/tripal_chado.property.api.php
  tripal_chado/src/api/tripal_chado.query.api.php
  tripal_chado/tests/src/Functional/api/ChadoCvAPITest.php
  tripal_chado/tests/src/Functional/api/ChadoDbAPITest.php
  tripal_chado/tests/src/Functional/api/ChadoQueryAPITest.php
  tripal_chado/tests/src/Functional/api/ChadoVariablesAPITest.php
Labels: Group 2 - Data Storage | Tripal DBX | Chado

#2297 Remove deprecated functions from importers
  phpunit.xml
  tripal_chado/src/Plugin/TripalImporter/FASTAImporter.php
  tripal_chado/src/Plugin/TripalImporter/GFF3Importer.php
  tripal_chado/src/Plugin/TripalImporter/NewickImporter.php
  tripal_chado/src/Plugin/TripalImporter/OBOImporter.php
  tripal_chado/src/Plugin/TripalImporter/TaxonomyImporter.php
  tripal_chado/src/Plugin/TripalImporter/TreeGenerator.php
  tripal_chado/src/api/tripal_chado.organism.api.php
  tripal_chado/src/api/tripal_chado.phylotree.api.php
  tripal_chado/tests/src/Kernel/api/ChadoOrganismAPITest.php
  tripal_chado/tests/src/Kernel/api/ChadoPhylogenyAPITest.php
Labels: Priority - Release Blocker, bug - potential, Group 0 - Maintenance | Docker | Misc, Group 9 - Automated Testing, Ready to Merge :tada:
